name: AoC Maven Java Part

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PACKAGE_ROOT: ./Java/launcher/target
  PROJECT_VERSION: 1.0-SNAPSHOT

jobs:
  downloadInput:
    uses: ./.github/workflows/AoC_Download.yml
    secrets: 
      AOC_SESSION_COOKIE: ${{secrets.AOC_SESSION_COOKIE}}

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        year-folder: [Java/2023/main/year2023]

    runs-on: ${{ matrix.os }}
    needs: downloadInput
    steps:
      - uses: actions/checkout@v4          
      - name: setup JDK
        uses: actions/setup-java@v4
        with:  
          distribution: 'microsoft'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: | # optional
            Java/**/pom.xml

      - name: Download input
        uses: actions/download-artifact@v4
        with:
          name: AoC_Input
          path: |
            ./

      - name: Maven package install
        run: |
          mvn --batch-mode --update-snapshots package install

      - name: Generate results
        run: |
          mvn exec:exec
          
      - name: Updload results
        uses: actions/upload-artifact@v4
        with:
          name: RESULTS-${{ matrix.os }}
          path: |
            ${{matrix.year-folder}}/*.log

  run:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        year-folder: [Java/2023/main/year2023]
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Prepare results
        uses: actions/download-artifact@v4
        with:
          name: RESULTS-${{ matrix.os }}
          path: |
            ${{matrix.year-folder}}/ActionResults
      
      - name: Print results log files
        working-directory: ${{matrix.year-folder}}/ActionResults
        run: |
          cat res.log
          cat exception.log
      
      - name: Diff results
        working-directory: ${{matrix.year-folder}}/ActionResults
        shell: bash
        run: |
          sh ${{github.workspace}}/.github/workflows/diff_file.sh res.log ../res.log


  report-if-diff-fail:
    runs-on: ubuntu-latest
    needs: run
    if: ${{ failure() }}
    steps:
      - run: |
          echo "FAILED"
