name: AoC CMake C++ Part

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release
  BUILD_DIR: build
  INSTALL_PREFIX: build/install

jobs:
  downloadInput:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - run: |
          python -m pip install --upgrade pip
          pip install -r InputDownloader/requirements.txt

      - name: Download AoC inputs
        env:
          AOC_SESSION_COOKIE: ${{ secrets.AOC_SESSION_COOKIE }}
        run: |
          python InputDownloader/downloader.py

      - name: Upload AoC inputs
        uses: actions/upload-artifact@v4
        with:
          name: AoC_Input
          path: |
            ./**/input.txt

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            preset: "unix-release"
          - os: windows-latest
            preset: "windows-gcc-release"

    runs-on: ${{ matrix.os }}
    needs: downloadInput
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download input
        uses: actions/download-artifact@v4
        with:
          name: AoC_Input
          path: |
            ./

      # - name: Restore CMake build files
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ env.BUILD_DIR }}
      #     key: cmake-${{ matrix.os }}-${{ matrix.preset }}-${{ hashFiles('**/*.cpp **/*.h') }}

      - name: Configure CMake
        # if: steps.cache-cmake.outputs.cache-hit != 'true'
        id: cmake-configure
        run: |
          cmake --list-presets
          cmake --preset=${{ matrix.preset }}

      - if: ${{ failure() }}
        run: |
          cmake --preset=default

      - name: Build project
        # if: steps.cache-cmake.outputs.cache-hit != 'true'
        run: |
          cmake --build --preset=${{ matrix.preset }}

      - name: Install binary
        run: |
          cmake --install ${{ env.BUILD_DIR }}/${{ matrix.preset }} --prefix=${{ env.INSTALL_PREFIX }}

      # - name: Cache CMake build files
      #   if: steps.cache-cmake.outputs.cache-hit != 'true'
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ env.BUILD_DIR }}
      #     key: cmake-${{ matrix.os }}-${{ matrix.preset }}-${{ hashFiles('**/*.cpp' '**/*.h') }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: BINARY-${{ matrix.os }}
          path: |
            **/res.log
            ${{ env.INSTALL_PREFIX }}

  run:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        year: [2024]
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: BINARY-${{ matrix.os }}
          path: |
            .

      - name: Generate results log files (linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: ${{ env.INSTALL_PREFIX }}/AoC/${{ matrix.year }}
        shell: bash
        run: |
          chmod u+x ./solution
          ./solution 1>actionRes.log 2>runtime.log

      - name: Generate results log files (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        working-directory: ${{ env.INSTALL_PREFIX }}/AoC/${{ matrix.year }}
        shell: cmd
        run: |
          .\solution 1>actionRes.log 2>runtime.log 
          type actionRes.log
          type runtime.log

      - name: Diff files
        shell: bash
        run: |
          if ! diff -u ${{ env.INSTALL_PREFIX }}/AoC/${{ matrix.year }}/actionRes.log ${{ matrix.year }}/res.log > diff.log; then
            echo "::error::Files differ. See diff.log for details."
            cat diff.log
            exit 1
          else
            echo "All pass"
          fi

      - name: Upload artifacts on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: run-failure-${{ matrix.os }}-${{ matrix.year }}
          path: |
            diff.log

      - name: LogResults
        shell: bash
        working-directory: ${{ env.INSTALL_PREFIX }}/AoC/${{ matrix.year }}
        run: |
          cat actionRes.log
          cat runtime.log

  report-if-diff-fail:
    runs-on: ubuntu-latest
    needs: run
    if: ${{ failure() }}
    steps:
      - run: |
          echo "FAILED"
