name: AoC CMake Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release
  BUILD_DIR: build

jobs:
  build-and-test:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r utils/InputDownloader/requirements.txt

    - name: Download AoC inputs
      env:
        AOC_SESSION_COOKIE: ${{ secrets.AOC_SESSION_COOKIE }}
      run: |
        python utils/InputDownloader/downloader.py

    - name: Configure CMake
      run: |
        cmake -S . -B ${{ env.BUILD_DIR }} -G "Ninja" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build project
      run: |
        cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}

    - name: Run tests (Linux) Generate results log files
      working-directory: ${{ env.BUILD_DIR }}/2024
      shell: bash
      run: |
        pwd && ls && ./solution 1>actionRes.log 2>runtime.log 
        cat actionRes.log
        cat runtime.log
        
    - name: Diff files and fail if different
      run: |
        if ! diff -u ${{ env.BUILD_DIR }}/2024/actionRes.log ./2024/res.log > diff.log; then
          echo "::error::Files differ. See diff.log for details."
          cat diff.log
          exit 1
        else
          echo "All pass"
        fi
        
    - name: Upload artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-output-${{ runner.os }}
        path: |
          ${{ env.BUILD_DIR }} 
          diff.log