name: AoC Python Part

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.12"

jobs:
  downloadInput:
    uses: ./.github/workflows/AoC_Download.yml
    secrets: 
      AOC_SESSION_COOKIE: ${{secrets.AOC_SESSION_COOKIE}}

  build-and-run:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        year-folder: [Python/2022/main/year2022]

    runs-on: ${{ matrix.os }}
    needs: downloadInput
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Download input
        uses: actions/download-artifact@v4
        with:
          name: AoC_Input
          path: |
            ./

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run Python solutions
        working-directory: Python/launcher
        run: |
          python runner.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: RESULTS-PYTHON-${{ matrix.os }}
          path: |
            ${{matrix.year-folder}}/*.log

  log:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        year-folder: [Python/2022/main/year2022]
    runs-on: ${{ matrix.os }}
    needs: build-and-run
    steps:
      - uses: actions/checkout@v4

      - name: Prepare results
        uses: actions/download-artifact@v4
        with:
          name: RESULTS-PYTHON-${{ matrix.os }}
          path: |
            ${{matrix.year-folder}}/ActionResults

      - name: Print results log files
        working-directory: ${{matrix.year-folder}}/ActionResults
        run: |
          cat res.log
          cat exception.log
      
      - name: Diff results
        shell: bash
        run: |
          sh ./.github/workflows/diff_file.sh ${{matrix.year-folder}}/ActionResults/res.log ${{matrix.year-folder}}/ActionResults/../res.log

  report-if-diff-fail:
    runs-on: ubuntu-latest
    needs: log
    if: ${{ failure() }}
    steps:
      - run: |
          echo "FAILED"