name: AoC Maven Java Part

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CLASS_PATHS: |
    Java/2023/target/classes
    Java/2023/target/classes
    Java/2023/target/classes
  PROJECT_VERSION: 1.0-SNAPSHOT

jobs:
  downloadInput:
    uses: ./.github/workflows/AoC_Download.yml
    secrets: 
      AOC_SESSION_COOKIE: ${{secrets.AOC_SESSION_COOKIE}}

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
          - os: windows-latest

    runs-on: ${{ matrix.os }}
    needs: downloadInput
    steps:
      - uses: actions/checkout@v4          
      - name: setup JDK
        uses: actions/setup-java@v4
        with:  
          distribution: 'microsoft'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: | # optional
            Java/**/*.pom

      - name: Maven verify
        run: |
          mvn --batch-mode --update-snapshots package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: JAR-${{ matrix.os }}
          path: |
            ./Java/launcher/target/launcher-${{env.PROJECT_VERSION}}.jar

  run:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        year-folder: [Java/2023/main/year2023]
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: JAR-${{ matrix.os }}
          path: |
            .

      - name: Download input
        uses: actions/download-artifact@v4
        with:
          name: AoC_Input
          path: |
            ./

      - name: Generate results log files (linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        shell: bash
        working-directory: ${{matrix.year-folder}}
        run: |
          java -ea -jar ..\..\..\launcher\target\launcher-1.0-SNAPSHOT-shaded.jar

      - name: Generate results log files (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        shell: cmd
        working-directory: ${{matrix.year-folder}}
        run: |
          java -ea -jar ..\..\..\launcher\target\launcher-1.0-SNAPSHOT-shaded.jar

  report-if-diff-fail:
    runs-on: ubuntu-latest
    needs: run
    if: ${{ failure() }}
    steps:
      - run: |
          echo "FAILED"
