name: CMake Build 2024 Solution

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner for MinGW builds

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Configure CMake with MinGW
      run: |
        mkdir .\2024\build && cmake -S .\2024 -B .\2024\build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release

    - name: Run executable on Windows
      run: |
        # Run the executable on Windows (using MinGW, executable will have .exe extension)
        cd .\2024 && ..\build\2024\solution.exe
      shell: cmd